name: GLaDOS Checkin

on:
  schedule:
    - cron: '15 1 * * *' # 每天 UTC 1:15 运行 (北京时间 9:15)
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        uses: octokit/request-action@v2 # 正确的 uses 路径
        with:
          route: POST /api/user/checkin
          baseUrl: 'https://glados.space'
          body: |
            {
              "token": "glados.one"
            }
          headers:
            authorization: "34275512987024078450447812440453-982-1512"
            content-type: application/json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 保留以备将来使用
