name: GLaDOS Checkin

on:
  schedule:
    - cron: '15 1 * * *' # 每天 UTC 1:15 运行 (北京时间 9:15)
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-22.04 # 明确指定 Ubuntu 版本
    steps:
      - name: Checkin
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.request('POST https://glados.space/api/user/checkin', {
              headers: {
                'Authorization': '34275512987024078450447812440453-982-1512',
                'Content-Type': 'application/json'
              },
              data: {
                token: 'glados.one'
              }
            });
            console.log(response);
